# Generated by Django 5.1 on 2024-10-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomstore', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_code',
            field=models.IntegerField(default='', unique=True),
        ),
    ]
